USE [HADB001]
GO


BEGIN TRANSACTION


/*****************************/
USE [HADB001]
GO


CREATE PARTITION FUNCTION [HADB_DATA_PART_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_DATA_PART_SCHEME1] AS PARTITION [HADB_DATA_PART_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])






ALTER TABLE [dbo].[HADB_DATA] DROP CONSTRAINT [PK_DATA] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[HADB_DATA] ADD  CONSTRAINT [PK_DATA] PRIMARY KEY NONCLUSTERED 
(
	[DATA_UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_DATA_PART_SCHEME1_637770265238480494] ON [dbo].[HADB_DATA]
(
	[DATA_SYSTEMNAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE ON PARTITIONS (1 TO 26)) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])


DROP INDEX [ClusteredIndex_on_HADB_DATA_PART_SCHEME1_637770265238480494] ON [dbo].[HADB_DATA]








SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [DATA_KEY1] ON [dbo].[HADB_DATA]
(
	[DATA_KEY1] ASC,
	[DATA_SYSTEMNAME] ASC,
	[DATA_NAMESPACE] ASC,
	[DATA_TYPE] ASC
)
WHERE ([DATA_ARCHIVE]=(0) AND [DATA_DELETED]=(0) AND [DATA_KEY1]<>'')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [DATA_KEY2] ON [dbo].[HADB_DATA]
(
	[DATA_KEY2] ASC,
	[DATA_SYSTEMNAME] ASC,
	[DATA_NAMESPACE] ASC,
	[DATA_TYPE] ASC
)
WHERE ([DATA_ARCHIVE]=(0) AND [DATA_DELETED]=(0) AND [DATA_KEY2]<>'')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [DATA_KEY3] ON [dbo].[HADB_DATA]
(
	[DATA_KEY3] ASC,
	[DATA_SYSTEMNAME] ASC,
	[DATA_NAMESPACE] ASC,
	[DATA_TYPE] ASC
)
WHERE ([DATA_ARCHIVE]=(0) AND [DATA_DELETED]=(0) AND [DATA_KEY3]<>'')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [DATA_KEY4] ON [dbo].[HADB_DATA]
(
	[DATA_KEY4] ASC,
	[DATA_SYSTEMNAME] ASC,
	[DATA_NAMESPACE] ASC,
	[DATA_TYPE] ASC
)
WHERE ([DATA_ARCHIVE]=(0) AND [DATA_DELETED]=(0) AND [DATA_KEY4]<>'')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])







SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [DATA_KEY5] ON [dbo].[HADB_DATA]
(
	[DATA_KEY5] ASC,
	[DATA_SYSTEMNAME] ASC,
	[DATA_NAMESPACE] ASC,
	[DATA_TYPE] ASC
)
WHERE ([DATA_ARCHIVE]=(0) AND [DATA_DELETED]=(0) AND [DATA_KEY5]<>'')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_LABEL1] ON [dbo].[HADB_DATA]
(
	[DATA_LABEL1] ASC
)
WHERE ([DATA_LABEL1]<>'' AND [DATA_DELETED]=(0) AND [DATA_ARCHIVE]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_LABEL2] ON [dbo].[HADB_DATA]
(
	[DATA_LABEL2] ASC
)
WHERE ([DATA_LABEL2]<>'' AND [DATA_DELETED]=(0) AND [DATA_ARCHIVE]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_LABEL3] ON [dbo].[HADB_DATA]
(
	[DATA_LABEL3] ASC
)
WHERE ([DATA_LABEL3]<>'' AND [DATA_DELETED]=(0) AND [DATA_ARCHIVE]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_LABEL4] ON [dbo].[HADB_DATA]
(
	[DATA_LABEL4] ASC
)
WHERE ([DATA_LABEL4]<>'' AND [DATA_DELETED]=(0) AND [DATA_ARCHIVE]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])






SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_LABEL5] ON [dbo].[HADB_DATA]
(
	[DATA_LABEL5] ASC
)
WHERE ([DATA_LABEL5]<>'' AND [DATA_DELETED]=(0) AND [DATA_ARCHIVE]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




CREATE NONCLUSTERED INDEX [DATA_SNAP_NO] ON [dbo].[HADB_DATA]
(
	[DATA_SNAPSHOT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_SYSTEMNAME] ON [dbo].[HADB_DATA]
(
	[DATA_SYSTEMNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [DATA_UID_ORIGINAL] ON [dbo].[HADB_DATA]
(
	[DATA_UID_ORIGINAL] ASC
)
WHERE ([DATA_ARCHIVE]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




CREATE NONCLUSTERED INDEX [DATA_UPDATE_DT] ON [dbo].[HADB_DATA]
(
	[DATA_CREATE_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])




CREATE NONCLUSTERED INDEX [DATA_VER] ON [dbo].[HADB_DATA]
(
	[DATA_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])








/*********************/

USE [HADB001]
GO

CREATE PARTITION FUNCTION [HADB_CONFIG_PART_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_CONFIG_PART_SCHEME1] AS PARTITION [HADB_CONFIG_PART_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])







ALTER TABLE [dbo].[HADB_CONFIG] DROP CONSTRAINT [PK_CONFIG] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[HADB_CONFIG] ADD  CONSTRAINT [PK_CONFIG] PRIMARY KEY NONCLUSTERED 
(
	[CONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_CONFIG_PART_SCHEME1_637770285801340289] ON [dbo].[HADB_CONFIG]
(
	[CONFIG_SYSTEMNAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [HADB_CONFIG_PART_SCHEME1]([CONFIG_SYSTEMNAME])


DROP INDEX [ClusteredIndex_on_HADB_CONFIG_PART_SCHEME1_637770285801340289] ON [dbo].[HADB_CONFIG]








SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [SYSTEM_NAME] ON [dbo].[HADB_CONFIG]
(
	[CONFIG_SYSTEMNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_CONFIG_PART_SCHEME1]([CONFIG_SYSTEMNAME])











/*************************/
USE [HADB001]
GO

CREATE PARTITION FUNCTION [HADB_KV_PART_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_KV_PART_SCHEME1] AS PARTITION [HADB_KV_PART_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])





ALTER TABLE [dbo].[HADB_KV] DROP CONSTRAINT [PK_HADV_KEY] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[HADB_KV] ADD  CONSTRAINT [PK_HADV_KEY] PRIMARY KEY NONCLUSTERED 
(
	[KV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_KV_PART_SCHEME1_637770287578041903] ON [dbo].[HADB_KV]
(
	[KV_SYSTEM_NAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [HADB_KV_PART_SCHEME1]([KV_SYSTEM_NAME])


DROP INDEX [ClusteredIndex_on_HADB_KV_PART_SCHEME1_637770287578041903] ON [dbo].[HADB_KV]








SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [KV_KEY] ON [dbo].[HADB_KV]
(
	[KV_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_KV_PART_SCHEME1]([KV_SYSTEM_NAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [KV_SYSTEM_NAME] ON [dbo].[HADB_KV]
(
	[KV_SYSTEM_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_KV_PART_SCHEME1]([KV_SYSTEM_NAME])










/***********************************/





USE [HADB001]
GO

CREATE PARTITION FUNCTION [HADB_LOG_PART_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_LOG_PART_SCHEME1] AS PARTITION [HADB_LOG_PART_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])






ALTER TABLE [dbo].[HADB_LOG] DROP CONSTRAINT [PK_HADB_LOG] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[HADB_LOG] ADD  CONSTRAINT [PK_HADB_LOG] PRIMARY KEY NONCLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_LOG_PART_SCHEME1_637770289959706596] ON [dbo].[HADB_LOG]
(
	[LOG_SYSTEM_NAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE ON PARTITIONS (1 TO 26)) ON [HADB_LOG_PART_SCHEME1]([LOG_SYSTEM_NAME])


DROP INDEX [ClusteredIndex_on_HADB_LOG_PART_SCHEME1_637770289959706596] ON [dbo].[HADB_LOG]








SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [LOG_LABEL1] ON [dbo].[HADB_LOG]
(
	[LOG_LABEL1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_LOG_PART_SCHEME1]([LOG_SYSTEM_NAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [LOG_LABEL2] ON [dbo].[HADB_LOG]
(
	[LOG_LABEL2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_LOG_PART_SCHEME1]([LOG_SYSTEM_NAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [LOG_LABEL3] ON [dbo].[HADB_LOG]
(
	[LOG_LABEL3] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_LOG_PART_SCHEME1]([LOG_SYSTEM_NAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [LOG_LABEL4] ON [dbo].[HADB_LOG]
(
	[LOG_LABEL4] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_LOG_PART_SCHEME1]([LOG_SYSTEM_NAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [LOG_SYSTEM_NAME] ON [dbo].[HADB_LOG]
(
	[LOG_SYSTEM_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_LOG_PART_SCHEME1]([LOG_SYSTEM_NAME])








/*****************************/







USE [HADB001]
GO

CREATE PARTITION FUNCTION [HADB_SNAPSHOT_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_SNAPSHOT_PART1] AS PARTITION [HADB_SNAPSHOT_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])






ALTER TABLE [dbo].[HADB_SNAPSHOT] DROP CONSTRAINT [PK_HADB_SNAP] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[HADB_SNAPSHOT] ADD  CONSTRAINT [PK_HADB_SNAP] PRIMARY KEY NONCLUSTERED 
(
	[SNAPSHOT_UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_SNAPSHOT_PART1_637770292244582182] ON [dbo].[HADB_SNAPSHOT]
(
	[SNAPSHOT_SYSTEM_NAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE ON PARTITIONS (1 TO 26)) ON [HADB_SNAPSHOT_PART1]([SNAPSHOT_SYSTEM_NAME])


DROP INDEX [ClusteredIndex_on_HADB_SNAPSHOT_PART1_637770292244582182] ON [dbo].[HADB_SNAPSHOT]








CREATE NONCLUSTERED INDEX [SNAP_DT] ON [dbo].[HADB_SNAPSHOT]
(
	[SNAPSHOT_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_SNAPSHOT_PART1]([SNAPSHOT_SYSTEM_NAME])




CREATE NONCLUSTERED INDEX [SNAP_NO] ON [dbo].[HADB_SNAPSHOT]
(
	[SNAPSHOT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_SNAPSHOT_PART1]([SNAPSHOT_SYSTEM_NAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [SNAP_SYSTEM_NAME] ON [dbo].[HADB_SNAPSHOT]
(
	[SNAPSHOT_SYSTEM_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_SNAPSHOT_PART1]([SNAPSHOT_SYSTEM_NAME])










/*****************************/


USE [HADB001]
GO

CREATE PARTITION FUNCTION [HADB_QUICK_PART_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_QUICK_PART_SCHEME1] AS PARTITION [HADB_QUICK_PART_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])







ALTER TABLE [dbo].[HADB_QUICK] DROP CONSTRAINT [PK_HADB_QUICK] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[HADB_QUICK] ADD  CONSTRAINT [PK_HADB_QUICK] PRIMARY KEY NONCLUSTERED 
(
	[QUICK_UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_QUICK_PART_SCHEME1_637778379394963243] ON [dbo].[HADB_QUICK]
(
	[QUICK_SYSTEMNAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [HADB_QUICK_PART_SCHEME1]([QUICK_SYSTEMNAME])


DROP INDEX [ClusteredIndex_on_HADB_QUICK_PART_SCHEME1_637778379394963243] ON [dbo].[HADB_QUICK]








SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [QUICK_KEY] ON [dbo].[HADB_QUICK]
(
	[QUICK_KEY] ASC,
	[QUICK_SYSTEMNAME] ASC,
	[QUICK_NAMESPACE] ASC,
	[QUICK_TYPE] ASC
)
WHERE ([QUICK_DELETED]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_QUICK_PART_SCHEME1]([QUICK_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [QUICK_SYSTEMNAME] ON [dbo].[HADB_QUICK]
(
	[QUICK_SYSTEMNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_QUICK_PART_SCHEME1]([QUICK_SYSTEMNAME])














/**********************/

USE [HADB001]
GO

CREATE PARTITION FUNCTION [HADB_STAT_PART_FUNC1](nvarchar(350)) AS RANGE RIGHT FOR VALUES (N'B', N'C', N'D', N'E', N'F', N'G', N'H', N'I', N'J', N'K', N'L', N'M', N'N', N'O', N'P', N'Q', N'R', N'S', N'T', N'U', N'V', N'W', N'X', N'Y', N'Z')


CREATE PARTITION SCHEME [HADB_STAT_PART_SCHEME1] AS PARTITION [HADB_STAT_PART_FUNC1] TO ([HADB001_FG_A], [HADB001_FG_B], [HADB001_FG_C], [HADB001_FG_D], [HADB001_FG_E], [HADB001_FG_F], [HADB001_FG_G], [HADB001_FG_H], [HADB001_FG_I], [HADB001_FG_J], [HADB001_FG_K], [HADB001_FG_L], [HADB001_FG_M], [HADB001_FG_N], [HADB001_FG_O], [HADB001_FG_P], [HADB001_FG_Q], [HADB001_FG_R], [HADB001_FG_S], [HADB001_FG_T], [HADB001_FG_U], [HADB001_FG_V], [HADB001_FG_W], [HADB001_FG_X], [HADB001_FG_Y], [HADB001_FG_Z])






ALTER TABLE [dbo].[HADB_STAT] DROP CONSTRAINT [PK_HADB_STAT] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[HADB_STAT] ADD  CONSTRAINT [PK_HADB_STAT] PRIMARY KEY NONCLUSTERED 
(
	[STAT_UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]


SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [ClusteredIndex_on_HADB_STAT_PART_SCHEME1_637770293237798341] ON [dbo].[HADB_STAT]
(
	[STAT_SYSTEMNAME]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE ON PARTITIONS (1 TO 26)) ON [HADB_STAT_PART_SCHEME1]([STAT_SYSTEMNAME])


DROP INDEX [ClusteredIndex_on_HADB_STAT_PART_SCHEME1_637770293237798341] ON [dbo].[HADB_STAT]








CREATE NONCLUSTERED INDEX [STAT_DT] ON [dbo].[HADB_STAT]
(
	[STAT_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_STAT_PART_SCHEME1]([STAT_SYSTEMNAME])




CREATE NONCLUSTERED INDEX [STAT_SNAPSHOT_NO] ON [dbo].[HADB_STAT]
(
	[STAT_SNAPSHOT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_STAT_PART_SCHEME1]([STAT_SYSTEMNAME])




SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [STAT_SYSTEMNAME] ON [dbo].[HADB_STAT]
(
	[STAT_SYSTEMNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_STAT_PART_SCHEME1]([STAT_SYSTEMNAME])









USE [HADB001]

GO

SET ANSI_PADDING ON


GO

CREATE UNIQUE CLUSTERED INDEX [UID_AND_SYSTEM_NAME] ON [dbo].[HADB_DATA]
(
	[DATA_UID] ASC,
	[DATA_SYSTEMNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [HADB_DATA_PART_SCHEME1]([DATA_SYSTEMNAME])

GO










/* ロックエスカレーション無効化 */
/*
ALTER TABLE HADB_CONFIG
SET ( LOCK_ESCALATION = DISABLE )

ALTER TABLE HADB_DATA
SET ( LOCK_ESCALATION = DISABLE )

ALTER TABLE HADB_KV
SET ( LOCK_ESCALATION = DISABLE )

ALTER TABLE HADB_LOG
SET ( LOCK_ESCALATION = DISABLE )

ALTER TABLE HADB_SNAPSHOT
SET ( LOCK_ESCALATION = DISABLE )

ALTER TABLE HADB_STAT
SET ( LOCK_ESCALATION = DISABLE )

ALTER TABLE HADB_QUICK
SET ( LOCK_ESCALATION = DISABLE )
*/


/* ロックエスカレーションを AUTO に設定 (パーティション分割している場合に効果的) */
ALTER TABLE HADB_CONFIG
SET ( LOCK_ESCALATION = AUTO )

ALTER TABLE HADB_DATA
SET ( LOCK_ESCALATION = AUTO )

ALTER TABLE HADB_KV
SET ( LOCK_ESCALATION = AUTO )

ALTER TABLE HADB_LOG
SET ( LOCK_ESCALATION = AUTO )

ALTER TABLE HADB_SNAPSHOT
SET ( LOCK_ESCALATION = AUTO )

ALTER TABLE HADB_STAT
SET ( LOCK_ESCALATION = AUTO )

ALTER TABLE HADB_QUICK
SET ( LOCK_ESCALATION = AUTO )



COMMIT TRANSACTION





USE [master]
GO



