name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-2019, windows-2022, windows-latest, macos-10.15, macos-11, macos-latest]
        dotnet-version: ["6.0"]

    steps:
      - name: Enable TLS 1.0 and 1.1 (disabled since windows-2022 GitHub custom images) 
        run: |
          New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -name 'Enabled' -value 1 -PropertyType 'DWord' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -name 'DisabledByDefault' -value 0 -PropertyType 'DWord' -Force | Out-Null
              
          New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -name 'Enabled' -value 1 -PropertyType 'DWord' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -name 'DisabledByDefault' -value 0 -PropertyType 'DWord' -Force | Out-Null
          
          Write-Host 'TLS 1.0 has been enabled.'


          New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -name 'Enabled' -value 1 -PropertyType 'DWord' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -name 'DisabledByDefault' -value 0 -PropertyType 'DWord' -Force | Out-Null
              
          New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -name 'Enabled' -value 1 -PropertyType 'DWord' -Force | Out-Null
              
          New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -name 'DisabledByDefault' -value 0 -PropertyType 'DWord' -Force | Out-Null
          
          Write-Host 'TLS 1.1 has been enabled.'

          $depencies = Get-Service HTTP -DependentServices |? Status -eq Running
          Stop-Service $depencies
          Restart-Service HTTP
          Start-Service $depencies
          Write-Host 'HTTP service restarted.'
        shell: pwsh
        if: matrix.operating-system == 'windows-2022'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Debug
        run: dotnet build -c Debug -v normal Cores.NET/Cores.NET-VS2022.sln

      - name: PrintRegKeys for Windows SSL Settings
        run: dotnet run --project Cores.NET/Dev.Test/Dev.Test.csproj --configuration Debug PrintRegKeys LocalMachine /key:SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL

      - name: Test Debug
        run: dotnet test -c Debug -v normal --logger:"console;verbosity=detailed" Cores.NET/Cores.NET-VS2022.sln

      - name: SslTestSuite Self Debug
        run: dotnet run --project Cores.NET/Dev.Test/Dev.Test.csproj --configuration Debug SslTestSuite self /parallel:64 /interval:1000 /ignore:default /expectedcertstr:default

      - name: Build Release
        run: dotnet build -c Release -v normal Cores.NET/Cores.NET-VS2022.sln

      - name: Test Release
        run: dotnet test -c Release -v normal --logger:"console;verbosity=detailed" Cores.NET/Cores.NET-VS2022.sln

      - name: SslTestSuite Self Release
        run: dotnet run --project Cores.NET/Dev.Test/Dev.Test.csproj --configuration Release SslTestSuite self /parallel:64 /interval:1000 /ignore:default /expectedcertstr:default

