name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, windows-2022, macOS-latest]
        dotnet-version: ["6.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Debug
        run: dotnet build -c Debug -v normal Cores.NET/Cores.NET-VS2022.sln

      - name: Test Debug
        run: dotnet test -c Debug -v normal --logger:"console;verbosity=detailed" Cores.NET/Cores.NET-VS2022.sln

      - name: SslTestSuite Self Debug
        run: dotnet run --project Cores.NET/Dev.Test/Dev.Test.csproj --configuration Debug SslTestSuite self /parallel:64 /interval:1000 /ignore:default /expectedcertstr:default

      - name: Build Release
        run: dotnet build -c Release -v normal Cores.NET/Cores.NET-VS2022.sln

      - name: Test Release
        run: dotnet test -c Release -v normal --logger:"console;verbosity=detailed" Cores.NET/Cores.NET-VS2022.sln

      - name: SslTestSuite Self Release
        run: dotnet run --project Cores.NET/Dev.Test/Dev.Test.csproj --configuration Release SslTestSuite self /parallel:64 /interval:1000 /ignore:default /expectedcertstr:default

